### PR TITLE
Replace 4.5.0-DP1 with 4.5.0-beta

### PR DESCRIPTION
**Pull request by Chippiewill**
This change is [Reviewable](https://reviewable.io/reviews/couchbaselabs/vagrants/27)

### CODE REVIEW

**Comment by mattcarabine** [comment]
Is Debian 8 still unsupported for the beta? It's in the docs!

**Comment by Chippiewill** [comment]
Technically no platform is supported :trollface:

**Comment by mattcarabine** [comment]
(see ninja edit)

**Comment by malarky** [comment]
I don't really think we need that warning any more.  I've been meaning to go through and update them so that we only have supported OS/CB variants in the list anyway.

**Comment by malarky** [comment]
👍

**Pull request merged**
