### PR TITLE
CBSP-2727: Support Community Editions

### PR DESCRIPTION
**Pull request by simon-dew**
[CBSP-2727](https://issues.couchbase.com/browse/CBSP-2727)

File structure changes:

* Add directory structure and vagrant files for `mad-hatter-community`, `alice-community`, and `vulcan-community`.

`Top_Level_Vagrantfile` changes:

* Add IP addresses for `mad-hatter-community`, `alice-community`, and `vulcan-community`.
* Update latest build numbers for `mad-hatter`, `alice`, and `vulcan`.
* Add download links for `mad-hatter-community`, `alice-community`, and `vulcan-community`.

### CODE REVIEW

**Comment by Tim020** [comment]
Hey @simon-dew, can you create a CBSP for this work being done please so we can track it :)

**Comment by simon-dew** [comment]
> Hey @simon-dew, can you create a CBSP for this work being done please so we can track it :)

Sure

**Comment by simon-dew** [comment]
Hmm, which board is that @Tim020 ?

**Comment by simon-dew** [comment]
Forgot to do fetch and rebase before pushing ...

**Comment by simon-dew** [comment]
Keeping this PR alive for reference. Feel free to reject and implement it another way.

**Comment by malarky** [comment]
Thanks @simon-dew, as we discussed, I think I have a pretty simple way of doing this :-)

**Comment by malarky** [comment]
Done in #133, closing this.

**Pull request closed without merging**
