### PR TITLE
Remove 4.1.0-testing, add 4.1.0-dp.

### PR DESCRIPTION
**Pull request by daverigby**

### CODE REVIEW

**Comment by malarky** [comment]
Hmm, you can probably remove the section from `couchbase_download_links` if the version (4.1.0-dp) matches the sub-dir and package names on S3.

**Comment by daverigby** [comment]
It's not quite the same - there's no "enterprise" in the filenames for 4.1.0-dp

**Comment by malarky** [comment]
OK, didn't spot that.  Hope that isn't another change in the package names again!

**Comment by malarky** [comment]
:+1:

**Pull request merged**
